# Generated by Django 6.0.4 on 2026-04-13 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friendrequest_status_onlinestatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineStatus',
        ),
    ]
