# Generated by Django 6.0.4 on 2026-04-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_onlinestatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineStatus',
        ),
    ]
